export const BLOCK_TYPES = {
  LINK: "LINK",
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  PDF: "PDF",
  FILE: "FILE",
  EMBED: "EMBED",
  QUOTE: "QUOTE",
  PAPER: "PAPER",
} as const;

export const EDGE_TYPES = {
  BLOCK_IN_CHANNEL: "BLOCK_IN_CHANNEL",
  BLOCK_HAS_TAG: "BLOCK_HAS_TAG",
  CHANNEL_IN_COLLECTION: "CHANNEL_IN_COLLECTION",
  RELATED_BY_SHARED_TAG: "RELATED_BY_SHARED_TAG",
  RELATED_BY_SHARED_CHANNEL: "RELATED_BY_SHARED_CHANNEL",
  RELATED_BY_SHARED_DOMAIN: "RELATED_BY_SHARED_DOMAIN",
  RELATED_BY_KEYWORD_OVERLAP: "RELATED_BY_KEYWORD_OVERLAP",
  RELATED_MANUAL: "RELATED_MANUAL",
  RELATED_BY_EMBEDDING: "RELATED_BY_EMBEDDING",
} as const;

export const NODE_TYPES = {
  BLOCK: "BLOCK",
  CHANNEL: "CHANNEL",
  TAG: "TAG",
  COLLECTION: "COLLECTION",
} as const;

export const VISIBILITY = {
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC",
  UNLISTED: "UNLISTED",
} as const;

export const GRAPH_SCORING = {
  SAME_CHANNEL: 5,
  SAME_TAG: 4,
  SAME_DOMAIN: 2,
  SHARED_KEYWORD: 2,
  SAME_WEEK: 1,
  MANUAL_RELATION: 10,
  MIN_SCORE_THRESHOLD: 6,
  MAX_AUTO_EDGES_PER_BLOCK: 12,
} as const;
