import { sqliteTable, text, integer, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  passwordHash: text("password_hash").notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const collections = sqliteTable("collections", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  color: text("color"),
  icon: text("icon"),
  visibility: text("visibility").default("PRIVATE"),
  createdById: text("created_by_id").references(() => users.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const channels = sqliteTable("channels", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  collectionId: text("collection_id").references(() => collections.id),
  visibility: text("visibility").default("PRIVATE"),
  createdById: text("created_by_id").references(() => users.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const blocks = sqliteTable("blocks", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  title: text("title"),
  content: text("content"),
  url: text("url"),
  normalizedUrl: text("normalized_url"),
  description: text("description"),
  imageUrl: text("image_url"),
  faviconUrl: text("favicon_url"),
  siteName: text("site_name"),
  domain: text("domain"),
  contentType: text("content_type"),
  note: text("note"),
  source: text("source"),
  extractedKeywords: text("extracted_keywords"),
  language: text("language"),
  isFavorite: integer("is_favorite").default(0),
  isArchived: integer("is_archived").default(0),
  createdById: text("created_by_id").references(() => users.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});


export const channelBlocks = sqliteTable("channel_blocks", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").references(() => channels.id).notNull(),
  blockId: text("block_id").references(() => blocks.id).notNull(),
  position: integer("position"),
  createdAt: integer("created_at").notNull(),
}, (table) => ({
  uniqueChannelBlock: uniqueIndex("unique_channel_block").on(table.channelId, table.blockId),
}));

export const tags = sqliteTable("tags", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  createdAt: integer("created_at").notNull(),
});

export const blockTags = sqliteTable("block_tags", {
  id: text("id").primaryKey(),
  blockId: text("block_id").references(() => blocks.id).notNull(),
  tagId: text("tag_id").references(() => tags.id).notNull(),
}, (table) => ({
  uniqueBlockTag: uniqueIndex("unique_block_tag").on(table.blockId, table.tagId),
}));

export const graphEdges = sqliteTable("graph_edges", {
  id: text("id").primaryKey(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id").notNull(),
  targetType: text("target_type").notNull(),
  targetId: text("target_id").notNull(),
  edgeType: text("edge_type").notNull(),
  weight: integer("weight").notNull(),
  reason: text("reason"),
  isAutoGenerated: integer("is_auto_generated").default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => ({
  uniqueEdge: uniqueIndex("unique_edge").on(
    table.sourceType, table.sourceId, table.targetType, table.targetId, table.edgeType
  ),
}));
