import { db } from "@/db";
import { graphEdges } from "@/db/schema";
import { getSessionFromRequest } from "@/lib/auth";
import { generateId, now } from "@/lib/utils";
import { eq } from "drizzle-orm";

export async function POST(request: Request) {
  try {
    const session = getSessionFromRequest(request);
    if (!session) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { sourceType, sourceId, targetType, targetId, edgeType, reason } = body;

    if (!sourceType || !sourceId || !targetType || !targetId || !edgeType) {
      return Response.json(
        { error: "sourceType, sourceId, targetType, targetId, and edgeType are required" },
        { status: 400 }
      );
    }

    const id = generateId();
    const timestamp = now();

    await db.insert(graphEdges).values({
      id,
      sourceType,
      sourceId,
      targetType,
      targetId,
      edgeType,
      weight: 10,
      reason: reason || null,
      isAutoGenerated: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    });

    const [created] = await db
      .select()
      .from(graphEdges)
      .where(eq(graphEdges.id, id))
      .limit(1);

    return Response.json(created, { status: 201 });
  } catch (error) {
    console.error("Create edge error:", error);
    return Response.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

export async function DELETE(request: Request) {
  try {
    const session = getSessionFromRequest(request);
    if (!session) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { edgeId } = body;

    if (!edgeId) {
      return Response.json(
        { error: "edgeId is required" },
        { status: 400 }
      );
    }

    await db.delete(graphEdges).where(eq(graphEdges.id, edgeId));

    return Response.json({ success: true });
  } catch (error) {
    console.error("Delete edge error:", error);
    return Response.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
